FROM ghcr.io/astral-sh/uv:python3.12-trixie-slim

ARG START_TIME

WORKDIR /app

COPY main.py settings.py pyproject.toml uv.lock .python-version ./scripts/entrypoint.sh ./

RUN chmod +x ./entrypoint.sh

ENV UV_NO_DEV=1

RUN uv sync --locked;

RUN BUILD_TIME=$(( $(date +%s) - $START_TIME)) && echo $BUILD_TIME > ./build_time.txt

ENV BASE_IMAGE=ghcr.io/astral-sh/uv:python3.12-trixie-slim

ENTRYPOINT ["./entrypoint.sh" ]
